Fix compatibility problem with python 3.6 and kill python 2 support
I got the following backtrace with python 3.6 (which is still
supported and default on some distribution).

And testing with python2 seemed to complicated, so I simply removed
the text kwarg and called .decode() on the result.

See
https://docs.python.org/3.6/library/subprocess.html#subprocess.check_output

as opposed to:

https://docs.python.org/3.7/library/subprocess.html#subprocess.check_output

I don't know what would be necessary to still support python 2, also
that would entail support for 3 different python versions.

~~~python
08:29 python: stdout/stderr: (tmux_env): Traceback (most recent call last):
08:29 python: stdout/stderr: (tmux_env):   File "/home/delgado/.weechat/python/autoload/tmux_env.py", line 101, in timer_cb
08:29 python: stdout/stderr: (tmux_env):     update_environment()
08:29 python: stdout/stderr: (tmux_env):   File "/home/delgado/.weechat/python/autoload/tmux_env.py", line 119, in update_environment
08:29 python: stdout/stderr: (tmux_env):     env = subprocess.check_output(['tmux', 'showenv'], **check_output_kwargs)
08:29 python: stdout/stderr: (tmux_env):   File "/usr/lib64/python3.6/subprocess.py", line 356, in check_output
08:29 python: stdout/stderr: (tmux_env):     **kwargs).stdout
08:29 python: stdout/stderr: (tmux_env):   File "/usr/lib64/python3.6/subprocess.py", line 423, in run
08:29 python: stdout/stderr: (tmux_env):     with Popen(*popenargs, **kwargs) as process:
08:29 python: stdout/stderr: (tmux_env): TypeError: __init__() got an unexpected keyword argument 'text'
~~~